apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    # 指定使用的 Ingress Class
    kubernetes.io/ingress.class: "nginx"
    # 讓後端 API 的路徑重寫（如果是 /api/xxx 會轉成 /xxx 給後端）
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # 連動 Cert-manager
spec:
  tls: # --- 新增這個區段 ---
    - hosts:
        - www.wishwithheart.com
      secretName: wishwithheart-tls # 憑證會存放在這裡
  rules:
    - host: www.wishwithheart.com
      http:
        paths:
          - path: /api/(.*) # 使用正則表達式捕獲路徑
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-service
                port:
                  number: 8080
          - path: /?(.*) # 其他流量導向前端
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
